// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBujFx4h-YB6B3Z9H2omnA29Hdc8Dq-a2g',
    appId: '1:605030970234:web:82215ac82786a589869cc3',
    messagingSenderId: '605030970234',
    projectId: 'laundry-bbc43',
    authDomain: 'laundry-bbc43.firebaseapp.com',
    databaseURL: 'https://laundry-bbc43-default-rtdb.firebaseio.com',
    storageBucket: 'laundry-bbc43.appspot.com',
    measurementId: 'G-PMXVQ5CGGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg0SZZ_jYxC0o3tV6ysS5kpimGmoWB0N4',
    appId: '1:605030970234:android:4e03771d9edd7e9c869cc3',
    messagingSenderId: '605030970234',
    projectId: 'laundry-bbc43',
    databaseURL: 'https://laundry-bbc43-default-rtdb.firebaseio.com',
    storageBucket: 'laundry-bbc43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2OuafvNJT3hHQDE63CNZ7CJqR5UJ_85w',
    appId: '1:605030970234:ios:38a2f8a1cac39184869cc3',
    messagingSenderId: '605030970234',
    projectId: 'laundry-bbc43',
    databaseURL: 'https://laundry-bbc43-default-rtdb.firebaseio.com',
    storageBucket: 'laundry-bbc43.appspot.com',
    iosBundleId: 'com.example.laundryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2OuafvNJT3hHQDE63CNZ7CJqR5UJ_85w',
    appId: '1:605030970234:ios:4f061a5e7abf652e869cc3',
    messagingSenderId: '605030970234',
    projectId: 'laundry-bbc43',
    databaseURL: 'https://laundry-bbc43-default-rtdb.firebaseio.com',
    storageBucket: 'laundry-bbc43.appspot.com',
    iosBundleId: 'com.example.laundryApp.RunnerTests',
  );
}
